//! Repositories.
//!
//! Two shapes live here, deliberately:
//!
//! * `Pg{Model}Repository` structs generated by `#[autumn_web::repository]`.
//!   They own a connection pool and are the right thing for route handlers —
//!   `PgRunRepository::from_request` / `with_pool_untracked`.
//! * Hand-written `async fn`s taking `&mut AsyncPgConnection`. They are the
//!   right thing for workflow **activities**, which already hold a connection
//!   and often need several operations inside one transaction. Taking the
//!   connection rather than the pool is also what makes them directly unit
//!   testable.

pub mod frame_queries;
pub mod frame_repository;
pub mod run_repository;
pub mod run_signal_repository;
pub mod scenario_repository;

pub use frame_queries::{frames_for_run, insert_frames_idempotent, max_tick, tick_gaps};
pub use frame_repository::{FrameRepository, PgFrameRepository};
pub use run_repository::{PgRunRepository, RunRepository};
pub use run_signal_repository::{PgRunSignalRepository, RunSignalRepository};
pub use scenario_repository::{PgScenarioRepository, ScenarioRepository};
